### ISSUE TITLE
port to Ember 1.6?

### ISSUE THREAD

**Issue by FezVrasta** [vvscode/js--ember-render-helper#1]
Hi, I'm trying to port this helper to 1.6 but I'm having troubles with `view.getStream`, do you know how could I workaround the problem? Seems like this function wasn't implemented yet in 1.6

**Comment by vvscode** [comment]
@FezVrasta  sorry. I miss your message. I don't this it worth to port down to Ember 1.6 
If it still actual for you -- contact with me ( just answer me ) and we'll try to do it together

**Comment by FezVrasta** [comment]
I just gave up :/ thanks however!
